export const ADD_PRODUCT='ADD_PRODUCT';
export const ADD_PRODUCT_OK='ADD_PRODUCT_OK';
export const ADD_PRODUCT_ERROR='ADD_PRODUCT_ERROR';

export const GET_PRODUCTS='GET_PRODUCTS';
export const GET_PRODUCTS_OK='GET_PRODUCTS_OK';
export const GET_PRODUCTS_ERROR='GET_PRODUCTS_ERROR';

export const DELETE_PRODUCT='DELETE_PRODUCTS';
export const DELETE_PRODUCT_ERROR='DELETE_PRODUCTS_ERROR';
export const DELETE_PRODUCT_OK='DELETE_PRODUCTS_OK';

export const PUT_PRODUCT='PUT_PRODUCTS';

export const UPDATE_PRODUCT='UPDATE_PRODUCTS';
export const UPDATE_PRODUCT_ERROR='UPDATE_PRODUCTS_ERROR';
export const UPDATE_PRODUCT_OK='UPDATE_PRODUCTS_OK';
